START TRANSACTION;
SET AUTOCOMMIT = 0;

CREATE TABLE Players (
	PlayerID varchar(50) NOT NULL,
	LungCapacity INT UNSIGNED NOT NULL DEFAULT 0,
	ShootingAbility INT UNSIGNED NOT NULL DEFAULT 0,
	Stamina INT UNSIGNED NOT NULL DEFAULT 0,
	Strength INT UNSIGNED NOT NULL DEFAULT 0,
	SkinModel varchar(50) NOT NULL DEFAULT "s_m_y_blackops_01",
	Weapons MEDIUMTEXT DEFAULT NULL,
	Kills INT UNSIGNED NOT NULL DEFAULT 0,
	Deaths INT UNSIGNED NOT NULL DEFAULT 0,
	Cash INT UNSIGNED NOT NULL DEFAULT 0,
	Banned TINYINT(1) NOT NULL DEFAULT 0,
	PRIMARY KEY (PlayerID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE Reports (
	PlayerID varchar(50) NOT NULL,
	Total INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY (PlayerID),
	FOREIGN KEY (PlayerID) REFERENCES Players(PlayerID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

COMMIT;